#!/bin/sh

# cat "$1" | sed 's/\(^[ ]*\)\(.*\)/\1'  > tmp


#cat $1  | awk '{print "BookmarkBegin"} 
#				{print "BookmarkPageNumber: " $NF}
#				{$NF=""; print "BookmarkTitle: " $0}
#				{print "BookmarkLevel: " gsub(/\./, ".", $1)+1}'

# Level PageNumber Title
cat "$1"  | awk ' 
	{gsub(/\t/,""); l=gsub(/\./, ".", $1)+1; pn=$NF; $NF=""; print l"\t"pn"\t"$0}
'


#cat tmp | grep "^[0-9]* " > tmp1
#cat tmp | grep "^[0-9]*\.[0-9]* " > tmp2
#cat tmp | grep "^[0-9]*\.[0-9]*\.[0-9]* " > tmp3

#cat tmp1 | awk '{printf $NF " "; $NF=""; print $0}' | tmp1
#cat tmp2 | awk '{printf $NF " "; $NF=""; print $0}' | tmp2
#cat tmp3 | awk '{printf $NF " "; $NF=""; print $0}' | tmp3
